### ISSUE TITLE
Authentication doesn't survive a refresh

### ISSUE THREAD

**Issue by John-Williams** [emollett/coffee-tracker#23]
I think there's something wrong with the authentication. if you refresh the /admin page while logged in, it'll tell you to login again.

**Comment by emollett** [comment]
Pull request #27 doesn't fix this but does stop the timing out after 1 minute. Still working on this bit.

**Comment by emollett** [comment]
Pull request #27 was wrong, pull request #28 reverts back to checkSession rather than parseHash which only works for the initial log in.
I've tried a couple of things in the audience bit - anything other than the management API url returns an error that the service doesn't exist
 This current returns an error saying login is required and still gets no authResult - {error: "login_required", error_description: "Login required"} when using google to authenticate
 If I use a non google log in the error I get is {error: "consent_required", error_description: "Consent required"} - I can however login again without going through the lock screen
In production, you time out after 1 minute rather than immediately whilst it is immediate locally. if you refresh or logout, you have to click login again, but you get taken right in (so the token still exists?). after 1 minute you get the error message - Could not get a new token (timeout: Timeout during executing web_message communication).
